name: Github Action/Workflow Linter

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ['*']
    paths:
      - '.github/actions/**'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install actionlint
        uses: supplypike/setup-bin@8e3f88b4f143d9b5c3497f0fc12d45c83c123787 # v4.0.1
        with:
          uri: 'https://github.com/rhysd/actionlint/releases/download/v1.7.7/actionlint_1.7.7_linux_amd64.tar.gz'
          name: 'actionlint'
          version: '1.7.7'

      - name: Run actionlint on changed files
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"

          changed_files=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep "^.github/workflows/.*\.yml$" || echo "")
          if [ -z "$changed_files" ]; then
            echo "No workflow files changed. Skipping lint."
            exit 0
          fi
          echo "Linting the following files:"
          echo "$changed_files"
          echo "$changed_files" | xargs actionlint -color
